admin:
  username: admin
  password: haha123
  timesheet: 999999
  full-user-initials: БулычевЕвгенийРоманович

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    name: admin
    password: secret
    url: jdbc:postgresql://localhost:5440/timeManagement

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

security:
  jwt:
    secret: EOzLwiTYwXYfRmiD
    expiration: 36000000
    subject: MyServerName